// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byrcdoddgrvhjqqbrcek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5cmNkb2RkZ3J2aGpxcWJyY2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NzQxNTMsImV4cCI6MjA2NTM1MDE1M30.6YkHOl695HS9X86sCKw1B6nfOy1vjD_mhUuXVmvvCFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);